require "json"

def generate_response_field_for_property(property_name, property_hash)
  if property_hash["type"] == "object"
    inner_fields = ""

    property_hash["properties"].each do |sub_property_name, sub_property_hash|
      inner_fields += generate_response_field_for_property(sub_property_name, sub_property_hash)
      inner_fields += "\n\n"
    end

    <<~EOF
      <ResponseField name="#{property_name}" type="#{property_hash["type"]}">
        <Expandable title="properties">
          #{inner_fields.gsub("\n", "\n    ")}
        </Expandable>
      </ResponseField>
    EOF
  elsif property_hash["type"] == "array"
    inner_fields = ""

    property_hash["items"]["properties"].each do |sub_property_name, sub_property_hash|
      inner_fields += generate_response_field_for_property(sub_property_name, sub_property_hash)
      inner_fields += "\n\n"
    end

    <<~EOF
      <ResponseField name="#{property_name}" type="#{property_hash["type"]}">
        <Expandable title="item properties">
          #{inner_fields.gsub("\n", "\n    ")}
        </Expandable>
      </ResponseField>
    EOF
  else
    <<~EOF
      <ResponseField name="#{property_name}" type="#{property_hash["type"]}">
        #{(property_hash["description"] || "").gsub("<", "&lt;").gsub(">", "&gt;")}
      </ResponseField>
    EOF
  end
end

json_schema = JSON.parse(File.read("docs/data/course_definition_schema.json"))

file_contents = <<~EOF
  ---
  # generated by scripts/generate_course_definition_reference.rb
  title: "Course Definition Reference"
  description: "Schema for the course-definition.yml file."
  ---
EOF

file_contents += "\n\n"

json_schema["properties"].each do |property_name, property_hash|
  file_contents += generate_response_field_for_property(property_name, property_hash)
  file_contents += "\n\n"
end

File.write("docs/authoring-challenges/course-definition-reference.mdx", file_contents)
